MODEL:
  MASK_ON: True
  PIXEL_MEAN:
    - 107.0
    - 148.0
    - 85.0
  PIXEL_STD:
    - 33.0
    - 34.0
    - 40.0
  # WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  WEIGHTS: "./models/segmentation_models/pretrained_M2F/model_final.pth" # You may need to change this path to point to your pretrained model
  META_ARCHITECTURE: "MaskFormer"
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 1 # set to 1 for instance segmentation of only foreground
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10 # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
  BACKBONE:
    FREEZE_AT: 10 # freeze the entire backbone
    NAME: "build_resnet_backbone"
  RESNETS:
    DEPTH: 50
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
SOLVER:
  IMS_PER_BATCH: 16
 
  #BASE_LR: 0.00001
  #MAX_ITER: 1000 #(500次迭代似乎不能使loss收敛，适当调大)
  #CHECKPOINT_PERIOD: 10000
  #WEIGHT_DECAY: 0.05
  #WARMUP_FACTOR: 1.0 # disable warmup
  #WARMUP_ITERS: 0

  # --- 学习率策略核心区 ---
  BASE_LR: 0.000005  # 初始学习率可以稍微大一点，因为后面会自动下降
  MAX_ITER: 5000   # 大大增加总训练迭代次数，给模型充分学习的时间

  LR_SCHEDULER_NAME: "WarmupCosineLR"

  WARMUP_ITERS: 500     # 在前500次迭代中进行“热身”
  WARMUP_FACTOR: 0.001 # 热身从一个很小的值开始
  WARMUP_METHOD: "linear"
  # --- 学习率策略结束 ---
  CHECKPOINT_PERIOD: 5000 # 可以设一个检查点，比如每5000次保存一下模型，以防中断
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: False # 如果你的GPU支持，可以设为True来加速训练
  
  #OPTIMIZER: "ADAMW"
  #CLIP_GRADIENTS:
    #ENABLED: True
    #CLIP_TYPE: "full_model"
    #CLIP_VALUE: 0.01
    #NORM_TYPE: 2.0
  #AMP:
    #ENABLED: False
TEST:
  EVAL_PERIOD: 50000 # dont evaluate during training
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 6
INPUT:
  SIZE_DIVISIBILITY: -1
  MASK_FORMAT: "bitmask"
  MIN_SIZE_TEST: 0 # disable resizing during testing
  FORMAT: "BGR"
  CROP:
    ENABLED: false
SEED: 42
VERSION: 2
DATASETS:
  TRAIN: ("Maskterial_Dataset",)
